### ISSUE TITLE
Scaffold routing and page construction

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/data-viewer#10]
We need to establish patterns for:

- How we create new routes
- Any rules/patterns we want to establish around routes (RESTfulness, state preservation, etc.)
- Where (in the project/filesystem) pages and components live

Some of this should probably be a side effect of Doing Other Work, so the real scope of this issue is to put a few stub items in the filesystem that demonstrate the patterns we want to follow.

**Comment by jasonaowen** [comment]
> - How we create new routes

#29!

> - Any rules/patterns we want to establish around routes (RESTfulness, state preservation, etc.)

I think we can get to this once we start building out a page that has state - does that sound reasonable? Like yeah, let's make RESTful routes, and let's use query parameters, and let's figure that all out once we have real things to do rather than in a template to throw away.

> - Where (in the project/filesystem) pages and components live

For now, I'm just putting components in `/src`; I figure once that starts feeling too crowded or messy we can move them to a subdirectory or so. If you have strong opinions, though, please share them! Otherwise, let's just say we'll figure this out later?

**Comment by reefdog** [comment]
Immediately upon starting #12, after delivering #27, I discovered that I _do_ have an opinion about where to store components and pages! I'll be opening a PR shortly with that change.

**Comment by jasonaowen** [comment]
Great! I'll unmark #29 as resolving this, so merging won't close it.
