### ISSUE TITLE
How do we deploy to production?

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/data-viewer#30]
_This is a low-priority, low-urgency discussion topic. No need to make any changes or decisions ahead of higher-priority delivery._

Currently, Netlify deploys `main` to the production URL automatically. I've [expressed a slight discomfort](https://github.com/PhilanthropyDataCommons/data-viewer/pull/28#issuecomment-1458430880) with this model. I fear that not having any limbo between "merge a PR" and "deploy to production" is both a little unexpected (is it intuitive that "merge this PR" means "going to production"?) and sets such a high standard for PR completeness that we risk leaving PRs open too long out of fear of whether it's ready for production or not.

What I think I prefer is to have a QA URL that reflects `main` at all times, but for the production deploy to be triggered by an actual [release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository). This decouples merging PRs into `main` from actual production deployment, while giving us a more explicit production deployment history if desired.

However, don't take the length of this message as reflective of passion. This is a loosely-held preference that I bring up in case it garners enough support to implement. If not, no worries!

**Comment by jasonaowen** [comment]
> sets such a high standard for PR completeness that we risk leaving PRs open too long out of fear of whether it's ready for production or not

This is a good concern to discuss! Thanks for raising this, @reefdog.

I've worked on teams that had a fear of deployments, and I believe that such fear is always a symptom of important, deeper problems. It can absolutely be a rational fear, and adding release gates and extra QA and so on can be a reasonable *short-term* solution, but the only sustainable solution is to address the root causes to allow for more frequent releases.

I believe PRs *should* be ready for production! And if folks are scared of merging a PR, then that PR is too big, too risky, or too untested to merge, and we should break it out into multiple, smaller, more testable PRs.

In this specific project, we're in a pilot state - velocity is critical, and if we break something, we can fix it through our regular development process; there are no uptime requirements that I'm aware of. At some point that will change, and then we will need to take additional care, but even then diffusing that release-readiness-check into each PR instead of fewer larger release gates is worthwhile; one of the agile aphorisms I agree with is "[if it hurts, do it more often](https://martinfowler.com/bliki/FrequencyReducesDifficulty.html)". We also have the PR deploys, which I hope will continue to work as we add auth, and which are very prod-like and give us a chance to perform that kind of QA.

**Comment by reefdog** [comment]
:100: All very well-reasoned!
