### ISSUE TITLE
Direct or intermediary PDC access?

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/data-viewer#4]
The data viewer is meant to be a thin view layer atop the data in the PDC. Ideally, the viewer would have no data layer whatsover; the most immediate exception to that would be user data (both identification and user preferences) if we decide to add individual user accounts for access control (see #3).

With that thinness in mind, we have two ways of fetching data from the PDC:

- **Direct**: The client (user's browser) requests data directly from the PDC service endpoints. Any resulting data transformation happens in the client.
- **Intermediary**: The client requests data from data-viewer backend endpoints, which internally proxy requests to the PDC service. The backend may do additional transformations to the data before sending it on to the client.

----

**Advantages to Direct**:
- Improved network performance, reducing two hops (browser → data-viewer backend → PDC service) to one (browser → PDC service).
- Simpler application design, since we don't need to build the proxy request architecture. In fact with this model the data-viewer may even be served statically (depending on the details from #3) with no executable backend.

**Disadvantages to Direct**:
- PDC service API key would be exposed, so security would have to be enforced based on request origin. I.e., it's not enough to recognize API key `abc123` as valid; the request would also have to come from a domain that the PDC recognized as valid for that key. This alone may be a deal-killer, unless we were already planning on it.

**Advantages to Intermediary**:
- No exposure of PDC service API key to the end user, so no need to restrict PDC service requests based on origin.
- It is possible (maybe even probable) that we will want to recompose the PDC service data into new models customized for the UX needs of the data viewer, and that it would be more performant to do so on the server (where it can potentially be cached and served to subsequent users) than by having each individual browser do it client-side. This is a complete spitball.

---

My assumption is that direct access would violate the authentication model of the PDC service — and that adding request origin restriction isn't in the architecture — and so direct access by a client browser isn't possible, and for that reason alone intermediary access is preferred.

But I wanted to be sure to put it out to the group in case someone could correct me or push the decision in a particular direction.

**Comment by bickelj** [comment]
The current authentication model of pre-shared API keys is intended to be a draft until we figure out the better solution. There is no current authorization model, for example, it's "if you have a valid key, you can authenticate and have access to all protected resources from anywhere."

My initial reaction is that we would prefer direct access but with a better authentication and authorization service. My hope is that the user would log in to a (future) Authorization Service (AS) rather than into the front-end UI and rather than into the back-end API implementation and that the AS provides tokens that the browser can use to access both front-end and back-end. If we end up using keycloak as the AS it would be something like this, although the diagram leaves out which entity is actually making the calls to which other agent in step 2 and I am assuming it is the still the browser still making direct calls: https://invidious.weblibre.org/watch?v=FyVHNJNriUQ&t=2200

**Comment by reefdog** [comment]
> My hope is that the user would log in to a (future) Authorization Service (AS) rather than into the front-end UI and rather than into the back-end API implementation and that the AS provides tokens that the browser can use to access both front-end and back-end.

So in this model, the data viewer's own access to the PDC service would be determined/dictated by a user having credentials for the PDC service?

I was operating under the assumption the data viewer would itself be an individual "client" of the PDC service, just like a GMS or any other integration, and any userland authentication in the data-viewer (#3) would be wholly separate. What you're describing is much more tightly-coupled and characterizes the data-viewer as very much a first-party extension of the PDC service… which may or may not be what we want.

We should definitely talk through this on Friday's meeting (or here, if folks want).

**Comment by reefdog** [comment]
I'll leave this open long enough for @jasonaowen to read up and weigh in if desired, but I think we came to the conclusion that the viewer will be a fully front-end only application that calls the API/service layer directly with no intermediary back-end.

**Comment by jasonaowen** [comment]
Yeah, this seems pretty well settled! I'll note that the authorization question is strongly related to #6; completing that task should prove that we don't need a dedicated back-end for this app, at least so far as authentication is concerned.

There are a few security implications here that are worth mentioning:
- as a public client, we'll use the [Authorization Code flow](https://oauth.net/2/grant-types/authorization-code/) with [PKCE](https://oauth.net/2/pkce/) (see also [Auth0's documentation](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-proof-key-for-code-exchange-pkce), which I find to be more approachable)
- as a public client, the client credentials alone should not be granted any access in Keycloak; in particular, the [Client Credentials flow](https://oauth.net/2/grant-types/client-credentials/) should be disabled for this client
- in order to retain the authentication token, we'll need to store it in the browser's local storage. [Auth0 details some of the browser storage tradeoffs](https://auth0.com/blog/secure-browser-storage-the-facts/); most relevantly, as a client without a dedicated back-end, we cannot use `HttpOnly` cookies, which are not vulnerable to XSS. We'll have to be careful about presenting data from the API (as of course we should anyway); my understanding is that it's all user-entered data, albeit with varying degrees of trust.

Please don't interpret any of this as suggesting a change in course; no intermediary back-end sounds like a good decision to me!

**Comment by reefdog** [comment]
10-4 to all of the above! @jasonaowen do you think we should copy out those links/notes to #6 (or a more granular task), or are they just ephemeral observations?

Even though this is closed, I'll add one more note: we would eventually (well past MVP) like to support persistent user settings such as preferred columns and certain application state, and in a way that doesn't just store it on a specific browser/machine (i.e., not just `localStorage`). Does Keycloak let us write any data back to the user record? I know Auth0 supports something like that through [custom user data](https://auth0.com/docs/microsites/manage-users/define-maintain-custom-user-data).

**Comment by bickelj** [comment]
@reefdog Hmm, there are hints that custom attributes are easy to set up (e.g. https://www.baeldung.com/keycloak-custom-user-attributes) but as for allowing the client/data-viewer to write these attributes to the user record, I am not sure how difficult that would be. It is certainly possible, but my sense is that it might be against the grain with keycloak. Part of me says "use local storage" but then I see how that would be frustrating for a user to have user preferences tied to a browser rather than the user in the auth system. I would say "assume it's possible but non-trivial" for now.

**Comment by reefdog** [comment]
@bickelj Okay, so that is something we'll need to consider (cc @jasonaowen). For MVP we can use local storage since we're mostly talking lightweight user preferences that are easy to recreate. But I can see us very quickly adding features (like preferred default columns) that a user may have spent more time on, and we'll want to persist across devices.

**Comment by jasonaowen** [comment]
>> There are a few security implications here that are worth mentioning:
>> 
>>  * as a public client, we'll use the [Authorization Code flow](https://oauth.net/2/grant-types/authorization-code/) with [PKCE](https://oauth.net/2/pkce/) (see also [Auth0's documentation](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-proof-key-for-code-exchange-pkce), which I find to be more approachable)
>> 
>>  * as a public client, the client credentials alone should not be granted any access in Keycloak; in particular, the [Client Credentials flow](https://oauth.net/2/grant-types/client-credentials/) should be disabled for this client
>> 
>>  * in order to retain the authentication token, we'll need to store it in the browser's local storage. [Auth0 details some of the browser storage tradeoffs](https://auth0.com/blog/secure-browser-storage-the-facts/); most relevantly, as a client without a dedicated back-end, we cannot use `HttpOnly` cookies, which are not vulnerable to XSS. We'll have to be careful about presenting data from the API (as of course we should anyway); my understanding is that it's all user-entered data, albeit with varying degrees of trust.
>
> do you think we should copy out those links/notes to https://github.com/PhilanthropyDataCommons/data-viewer/issues/6 (or a more granular task), or are they just ephemeral observations?

More documentation doesn't hurt! I'd say the first and last points are more implementation-level plans that will be realized in code, and I'll consider whether they should be checked in docs. The second point is an operational concern that I'll be sure to document in the README or so.

**Comment by jasonaowen** [comment]
>> we would eventually (well past MVP) like to support persistent user settings such as preferred columns and certain application state, and in a way that doesn't just store it on a specific browser/machine (i.e., not just localStorage). Does Keycloak let us write any data back to the user record?
>
> ...
> I would say "assume it's possible but non-trivial" for now.

I think when we get to that point, a dedicated back-end for this app will make more sense. I am hesitant to give IdP write access to tokens issued to a public client, and in general my mental model is that the IdP is not the right place for storing application-specific, non-auth-related user preferences. Maybe that is actually a common pattern, though, that I'm unfamiliar with?

**Comment by reefdog** [comment]
@jasonaowen I think it's fair to say it's an uncommon pattern. Auth0's support is probably in service to customer lock-in. (Charitably, maybe it's meeting a customer demand.) I'm happy to separate concerns and keep user preferences within the Data Viewer stack. It adds complexity, but at least it does so in the correct place.
