### ISSUE TITLE
Proof of concept authentication via Keycloak

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/data-viewer#6]
We need to build a skeletal, proof of concept authentication via Keycloak. The necessary workflow:

1. From the Data Viewer, click a Login link
2. Be taken to Keycloak to authenticate
3. Upon successful authentication, be sent back to Data Viewer
4. Data Viewer recognizes who you are and maintains a session
5. ~~Data Viewer is able to make API calls to the service layer using a token~~

Each of those must work for this task to be complete.

**Reference links:**

- [Auth.js + SvelteKit](https://authjs.dev/reference/sveltekit/modules/main)
- [Auth.js's documentation on Keycloak as a provider](https://authjs.dev/reference/oauth-providers/keycloak)

<details>
<summary><b>Stretch goals…</b></summary>

These niceties will probably be spun off to their own tasks since they're polish:

- Ensure the front end can gracefully handle the API's rejection of a token. (Verify it against Keycloak? Renew it and try again? Prompt to re-authenticate?)
- Password reset ← Update: This will almost certainly be handled entirely by the Keycloak installation.
- Account modification (email, password, etc.) ← Update: This will almost certainly be handled entirely by the Keycloak installation.
- ~Self-registration~ ← Update: This isn't even on the radar, scrap as a stretch goal.

</details>

**Comment by jasonaowen** [comment]
The [lack of a dedicated back-end](https://github.com/PhilanthropyDataCommons/data-viewer/issues/4) leads to a few security implications that are worth mentioning:
- as a public client, we'll use the [Authorization Code flow](https://oauth.net/2/grant-types/authorization-code/) with [PKCE](https://oauth.net/2/pkce/) (see also [Auth0's documentation](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-proof-key-for-code-exchange-pkce), which I find to be more approachable)
- as a public client, the client credentials alone should not be granted any access in Keycloak; in particular, the [Client Credentials flow](https://oauth.net/2/grant-types/client-credentials/) should be disabled for this client, and this operational concern should be documented in the setup instructions of this repo
- in order to retain the authentication token, we'll need to store it in the browser's local storage. [Auth0 details some of the browser storage tradeoffs](https://auth0.com/blog/secure-browser-storage-the-facts/); most relevantly, as a client without a dedicated back-end, we cannot use `HttpOnly` cookies, which are not vulnerable to XSS. We'll have to be careful about presenting data from the API (as of course we should anyway); my understanding is that it's all user-entered data, albeit with varying degrees of trust.

**Comment by jasonaowen** [comment]
With the token proof of concept split off into #11, I think this was finished via #35! Marking as complete.
