### ISSUE TITLE
Show fallback data in proposals list

### ISSUE THREAD

**Issue by jasonaowen** [PhilanthropyDataCommons/data-viewer#67]
In https://github.com/PhilanthropyDataCommons/data-viewer/pull/49#issuecomment-1499827957, @reefdog wrote:

> @jasonaowen Would you have time to add the `getValueOfCanonicalField` fallback chain to the proposal list table as well, for the same three effective fields (org name, org EIN, and proposal name)? Scanning the table and seeing much "missing data" that seems to fill in once you click through to the detail page, e.g.:
> 
> https://user-images.githubusercontent.com/4731/230523066-dd42048e-22ab-4cd8-be99-d8ac8fe7f8d6.mov

This is a more complex request than it might appear on the surface, particularly when it comes to allowing customization of columns (#18). Think through what this means, and what all fields we want to handle this way.

**Comment by reefdog** [comment]
Ergh, yes, it is indeed more complicated than the proposal detail page use. There, we were extracting a label to use elsewhere on the page (outside of the table context). Here, we're in a table, with a label. We probably can't go sticking "Organization Legal Name" in a column titled "Organization Name".

I think the real answer here is that even this very narrow set of fields assumes more data consistency and standardization than we might hope for.

**Comment by jasonaowen** [comment]
@reefdog is this a duplicate of #109? Now that we have commits and PR #114 referencing that one, should we close this in favor of that?

**Comment by jasonaowen** [comment]
Duplicate of #109

**Comment by reefdog** [comment]
@jasonaowen Yes, thank you for remembering (and closing) this!

Perhaps I was cavalier in my approach in PR #114 to not consider column customization, but I also think we've learned something since the original column-customization design, which is: this proposal list table is a navigation tool with some lightweight comparative features (think: sorting by a budget column). It's not meant to reflect a perfect field:value mapping like the detail tables should.

Thus, we can treat the columns "seriously, not literally" and do things like the Org Name cascade.

Which is to say, I agree with closing this one.
