### ISSUE TITLE
Bare navigation to root doesn't recognize authentication status

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/data-viewer#76]
It seems that loading the root landing page doesn't correctly recognize authentication status. If you navigate to the Dashboard page and then go back to the root (via clicking on the PDC logo or removing `/proposals` from the URL), then the landing page reflects your logged-in status. But of course that shouldn't be necessary.

**Steps to reproduce:**
1. Log in to the PDC, and then close the window.
2. Open a new window and go to the PDC root page.
3. ❌ The landing page should reflect a logged-in status ("Go to the Dashboard" button in landing panel; "[your name]" in navbar) but shows the logged-out status instead ("Log in" button in landing panel and navbar).

I'm probably using the [wrong methods](https://github.com/PhilanthropyDataCommons/data-viewer/blob/6e2d7b0332c0951c85d51ab6d9ebccfc6a16f3c5/src/pages/Landing.tsx#L16) from OIDC library, or need to run another function first.

**Comment by reefdog** [comment]
Update: When you go through the login process and get redirected back to the root from Keycloak, that version of the landing page _does_ display the correct auth status. Just, FYI.

**Comment by jasonaowen** [comment]
We are currently have the library's default of using [session storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) for its authentication tokens, rather than local storage. Closing the window you used to sign in and opening a new window would cause the browser to start a new session and discard the old session, so yes you would be logged out under that workflow.

(Note that this is the data-viewer session; Keycloak has its own session rules, and I believe its cookies are not browser-session-bound, and so you might still be logged in to Keycloak even though data-viewer has no valid authentication tokens; in that case, clicking the login button should be pretty quick and show no Keycloak pages.)

**Comment by reefdog** [comment]
Oh, interesting. I understand the problem now, great explanation.

Why is a more persistent storage location secure enough for Keycloak itself (and for most other sites) but not for us?

**Comment by jasonaowen** [comment]
@reefdog let me know if you still think this is worth working on!

**Comment by reefdog** [comment]
@jasonaowen Nah, I'm okay with where we landed. Thanks for the explanation!
